apiVersion: v1
kind: Service
metadata:
  name: hypercloud5-api-server-service
  namespace: hypercloud5-system
spec:
  ports:
    - name: "port1"
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    hypercloud5: api-server
  type: LoadBalancer
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypercloud5-api-server
  namespace: hypercloud5-system
  labels:
    hypercloud5: api-server
    name: hypercloud5-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      hypercloud5: api-server
  template:
    metadata:
      name: hypercloud5-api-server
      labels:
        hypercloud5: api-server
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        effect: "NoSchedule"
      #imagePullSecrets:
      #  - name : docker-pull-secret
      serviceAccount: hypercloud5-admin
      containers:
        - name: hypercloud5-api-server
          image: 192.168.6.197:5000/hc-test:v0.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: HC_MODE
              value: "multi"  # multi / single 
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: "1G"
            requests:
              cpu: "1"
              memory: "100M"
          volumeMounts:
          - name: config-module
            mountPath: /version 
      volumes:
      - name : config-module
        configMap:
          name : hc-version # configmap shoulde be already made before mount this
