apiVersion: v1
kind: ConfigMap
metadata:
  name: hc-version
  namespace: hypercloud4-system
data:
  module.config: |
    modules:
    - name: HyperCloud-Operator
      namespace:
      selector:
        matchLabels:
          statusLabel:
          - hypercloud5=operator
          versionLabel:
          - hypercloud5=operator
      readinessProbe:

      versionProbe:

    - name: HyperCloud-Console
      namespace:
      selector:
        matchLabels:
          statusLabel:
          - app=console
          versionLabel:
          - app=console
      readinessProbe:

      versionProbe:

    - name: HyperCloud-WebHook
      namespace:
      selector:
        matchLabels:
          statusLabel:
          - hypercloud5=webhook
          versionLabel:
          - hypercloud5=webhook
      readinessProbe:

      versionProbe:

    - name: HyperCloud-Watcher
      namespace:
      selector:
        matchLabels:
          statusLabel:
          - hypercloud5=secret-watcher
          versionLabel:
          - hypercloud5=secret-watcher
      readinessProbe:

      versionProbe:

    - name: Kubernetes
      namespace:
      selector:
        matchLabels:
          statusLabel:
          - component=kube-apiserver
          versionLabel:
          - component=kube-apiserver
      readinessProbe:

      versionProbe:

    - name: Calico
      namespace: kube-system
      selector:
        matchLabels:
          statusLabel:
          - k8s-app=calico-node
          versionLabel:
          - k8s-app=calico-node
      readinessProbe:

      versionProbe:

    - name: Rook-Ceph
      namespace: rook-ceph
      selector:
        matchLabels:
          statusLabel:
          - app=rook-ceph-operator
          versionLabel:
          - app=rook-ceph-tools
      readinessProbe:

      versionProbe:

    - name: Prometheus
      namespace: monitoring
      selector:
        matchLabels:
          statusLabel:
          - app=prometheus
          versionLabel:
          - app=prometheus
      readinessProbe:
        httpGet:
          path: /-/ready
          port: 9090
          scheme: HTTP
      versionProbe:
        container: prometheus


    - name: Grafana
      namespace: monitoring
      selector:
        matchLabels:
          statusLabel:
          - app=grafana
          versionLabel:
          - app=grafana
      readinessProbe:
        httpGet:
          path: /api/health
          port: 3000
      versionProbe:

    - name: Tekton
      namespace: tekton-pipelines
      selector:
        matchLabels:
          statusLabel:
          - app=tekton-pipelines-controller
          versionLabel:
          - app=tekton-pipelines-controller
      readinessProbe:

      versionProbe:

    - name: Tekton-Trigger
      namespace: tekton-pipelines
      selector:
        matchLabels:
          statusLabel:
          - app=tekton-triggers-controller
          versionLabel:
          - app=tekton-triggers-controller
      readinessProbe:

      versionProbe:

    - name: Catalog-Controller
      namespace: catalog
      selector:
        matchLabels:
          statusLabel:
          - app=catalog-catalog-controller-manager
          versionLabel:
          - app=catalog-catalog-controller-manager
      readinessProbe:
        httpGet:
          path: /healthz/ready
          port: 8444
          scheme: HTTPS
      versionProbe:

    - name: TemplateServiceBroker
      namespace:
      selector:
        matchLabels:
          statusLabel:
          - hypercloud5=template-service-broker
          versionLabel:
          - hypercloud5=template-service-broker
      readinessProbe:

      versionProbe:
