apiVersion: v1
kind: Service
metadata:
  name: hypercloud5-api-server-service
  namespace: hypercloud5-system
spec:
  ports:
    - name: "port1"
      port: 28678
      protocol: TCP
      targetPort: 80
  selector:
    hypercloud5: api-server
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypercloud5-api-server
  namespace: hypercloud5-system
  labels:
    hypercloud5: api-server
    name: hypercloud5-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      hypercloud5: api-server
  template:
    metadata:
      name: hypercloud5-api-server
      labels:
        hypercloud5: api-server
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: ck-2 # need to be changed per Env
      #imagePullSecrets:
      #  - name : docker-pull-secret
      containers:
        - name: hypercloud5-api-server
          image: 192.168.6.197:5000/hc-api-server:v0.1.0 #192.168.6.110:5000/hc-api-server:v0.0.3
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Seoul
          ports:
            - containerPort: 28678
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
          - name: api-server-log-mnt
            mountPath: /logs
          - name: config-module
            mountPath: /version 
      volumes:
      - name: api-server-log-mnt
        hostPath:
          path: /root/swlee/hypercloud-api-server/logs/ # need to be changed per Env
      - name : config-module
        configMap:
          name : hc-version # configmap shoulde be already made before mount this
      #serviceAccountName: hypercloud5-system-admin
