apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypercloud4-api-server
  namespace: hypercloud4-system
  labels:
    hypercloud4: api-server
    name: hypercloud4-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      hypercloud4: api-server
  template:
    metadata:
      name: hypercloud4-api-server
      labels:
        hypercloud4: api-server
    spec:
      containers:
        - name: hypercloud4-api-server
          image: 192.168.6.110:5000/hc-api-server:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Seoul
          ports:
            - containerPort: 28678
          volumeMounts:
            - name: config-module
              mountPath: /version
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
      serviceAccountName: hypercloud4-admin
      volumes:
        - name : config-module
          configMap:
            name: hc-version

---

apiVersion: v1
kind: Service
metadata:
  name: hypercloud4-api-server-service
  namespace: hypercloud4-system
spec:
  ports:
    - name: "port1"
      port: 28678
      protocol: TCP
      targetPort: 80
  selector:
    hypercloud4: api-server
  type: LoadBalancer
