apiVersion: v1
kind: Namespace
metadata:
  name: hypercloud5-system

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: hypercloud5-system-quota
  namespace: hypercloud5-system
spec:
  hard:
    limits.cpu: "3"
    limits.memory: "3Gi"
    requests.storage: "1Gi"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: hypercloud5-admin
  namespace: hypercloud5-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hypercloud5-admin
subjects:
- kind: ServiceAccount
  name: hypercloud5-admin 
  namespace: hypercloud5-system
roleRef:
  kind: ClusterRole  #this must be Role or ClusterRole
  name: cluster-admin  # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
  
---

#apiVersion: v1
#kind: Secret
#metadata:
#  name: docker-pull-secret
#  namespace: hypercloud5-system